### ISSUE TITLE
Can we insert data directly into the datatable from the arraylist ?

### ISSUE THREAD

**Issue by Chaitanyashetti** [Dimention-X/cSharpExamples#4]
trying to find the way.

**Comment by akhileshsh026** [comment]
hers's what i tried ,
ArrayList al = new ArrayList();
al.Add("Test1");
al.Add("Test2");
DataTable dt = new DataTable();
dt.Columns.Add("Columname");
foreach(string item in al)
{
dt.Rows.Add(item);
}
